spring:
  application:
    name: zcc-temp

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  上传文件大小限制
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# 线程池配置
  task:
    execution:
      pool:
        core-size: 3
        max-size: 6
        queue-capacity: 100
      thread-name-prefix: temp-thread-
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.18.22.73:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: K2pass!!

# 日志debug显示
logging:
  level:
    com:
      miya:
        dao: debug
mybatis-plus:
  configuration:
    lazy-loading-enabled: true
