spring:
  #  数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springboot-demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true
#    url: jdbc:mysql://43.142.243.245:3306/springboot-demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 12345678