spring:
#  profiles:
#    active: tencent

  application:
    name: zcc-temp

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  上传文件大小限制
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# 线程池配置
  task:
    execution:
      pool:
        core-size: 3
        max-size: 6
        queue-capacity: 100
      thread-name-prefix: temp-thread-

  #  数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useUnicode=true
    username: root
    password: 12345678
#   连接池
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
#     空闲连接存活最大时间，默认十分钟（600000）
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
#     心跳机制sql
      connection-test-query: SELECT 1
  thymeleaf:
    cache: false

# 日志debug显示
logging:
  level:
    com:
      miya:
        dao: debug
mybatis-plus:
  configuration:
    lazy-loading-enabled: true
  mapper-locations: classpath*:/mapper/**/*.xml
